# .github/workflows/douban.yml
name: douban
on: 
  workflow_dispatch:
  schedule:
  - cron: "0 0,0,12,23 * * *"
  watch:
    types: [started]

jobs:
  douban:
    name: Douban mark data sync
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: delete old file
      run: |
        rm -rf ./csv
    - name: movie
      uses: lizheming/doumark-action@master
      with:
        id: 266851825
        type: movie
        format: csv
        dir: ./csv/douban
  
    - name: Commit
      uses: EndBug/add-and-commit@v9
      with:
        message: 'chore: update douban data'
        add: './csv/douban'
